---

# SWIFT unused parameter file
# code version: 2026.04
# git revision: v2026.04-55-g4ee5b667
# git branch: master
# git date: 2026-07-03 10:24:07 +0200
# current date: 15:32:13 2026-07-13 PDT

SPH:
  delta_neighbours: 0.1
...
